In [1]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = st.mean(age)
print('Mean Age:',m_age)

Mean Age: 27.142857142857142


In [2]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = st.median(age)
print('Median Age:',m_age)

Median Age: 20


In [3]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = st.mode(age)
print('Mode Age:',m_age)

Mode Age: 20


In [4]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = st.stdev(age)
print('Variance Age:',m_age)

Variance Age: 18.942268180171133


In [5]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = st.variance(age)
print('Mean Age:',m_age)

Mean Age: 358.8095238095238


In [6]:
import statistics as st
age = [20, 19, 20, 18, 21, 22, 70]
m_age = max(age)- min(age)
print('Range Age: ',m_age)

Range Age:  52


In [7]:
import numpy as np

In [8]:
a1 = np.array(20)
print(a1)
print('dim',a1.ndim)

20
dim 0


In [9]:
a2 = np.array([10, 20, 30, 10, 30, 405, 505, 50, 50])
print(a2)
print('dim',a2.ndim)

[ 10  20  30  10  30 405 505  50  50]
dim 1


In [10]:
a3 = np.array([[10, 20, 30], [10, 30, 405], [505, 50, 50]])
print(a3)
print('dim',a3.ndim)
print('Shape',a3.shape)
print('Size',a3.size)
print('Item Size',a3.itemsize)
print('dtype',a3.dtype)

[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
dim 2
Shape (3, 3)
Size 9
Item Size 8
dtype int64


In [11]:
import pandas as pd

In [12]:
prod_dict = {
    'pid' : ['iphone','Galaxy','Realme','Nokia'],
    'price' : [85000, 60000, 25000, 15000],
    'vendor' :['Apple','Samsung','Realme','Nokia'],
}

prod_dict

{'pid': ['iphone', 'Galaxy', 'Realme', 'Nokia'],
 'price': [85000, 60000, 25000, 15000],
 'vendor': ['Apple', 'Samsung', 'Realme', 'Nokia']}

In [13]:
prod_df = pd.DataFrame(prod_dict)

prod_df

pid  price   vendor
0  iphone  85000    Apple
1  Galaxy  60000  Samsung
2  Realme  25000   Realme
3   Nokia  15000    Nokia

In [14]:
prod_df.size

12

In [15]:
prod_df.dtypes

pid       object
price      int64
vendor    object
dtype: object

In [16]:
prod_df.shape

(4, 3)

In [17]:
prod_df.values

array([['iphone', 85000, 'Apple'],
       ['Galaxy', 60000, 'Samsung'],
       ['Realme', 25000, 'Realme'],
       ['Nokia', 15000, 'Nokia']], dtype=object)

In [18]:
prod_df.columns

Index(['pid', 'price', 'vendor'], dtype='object')

In [19]:
prod_df.index

RangeIndex(start=0, stop=4, step=1)